/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictationor;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;


/**
 *
 * @author Administrator
 */
public class Dictation extends javax.swing.JDialog {
    
    private final int number;
    private final ArrayList<String> DictationList =new ArrayList<>(100);
    
    /**
     * Creates new form Dictation
     * @param parent
     * @param modal
     * @param number Number of words in the dictation
     */
    public Dictation(java.awt.Frame parent, boolean modal, int number) {
        super(parent, modal);
        this.number =number;
        initComponents();
        startDict();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setResizable(false);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        Console.setEditable(false);
        Console.setColumns(20);
        Console.setRows(5);
        jScrollPane1.setViewportView(Console);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );

        jButton1.setText("Replay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        new File("tools/voice.vbs").delete();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start ./tools/voice.vbs");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   private void startDict(){
       okButton.setEnabled(false);
       Console.append("Loading... \r\n\r\n");
       Console.setCaretPosition(Console.getText().length());
       IOMain.readWordList();
       initDictationList();
       for(String x:DictationList){
       Console.append(x+"\r\n");
       Console.setCaretPosition(Console.getText().length());
       }
       generateVoiceData();
       try {
            Runtime.getRuntime().exec("cmd.exe /c start ./tools/voice.vbs");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
       Console.append("\r\nComplete!...\r\n");
       Console.setCaretPosition(Console.getText().length());
       okButton.setEnabled(true);
   }
   
   private void initDictationList(){
       int total =IOMain.WORDLIST.size();
       for(int i =0;i<number;i++){
           int n =(int) (Math.random()*(total - 1));
           DictationList.add(IOMain.WORDLIST.get(n));
           IOMain.WORDLIST.remove(n);
       }
       
   }
   
   private void generateVoiceData(){
       String location ="tools/voice.vbs";
       String[] output1 =new String[]{
           "Set objVoice = CreateObject(\"SAPI.SpVoice\")", 
           "Set objVoice.Voice = objVoice.GetVoices(\"Name = VW Paul\").Item(0)",
           "objVoice.Rate = -2",
           "objVoice.Volume = 100"
       };
       IOMain.write(output1, location, false);
       String[] output2 =new String[number*2];
       for(int i =0,j =0;j<number;j++){
           String word =DictationList.get(j);
           output2[i++] ="objVoice.Speak \""+word+"\"";
           output2[i++] ="Wscript.Sleep 5000";
       }
       IOMain.write(output2, location, true);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Console;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
